export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const FETCH_PROJECTS_PENDING = 'FETCH_PROJECTS_PENDING';
export const FETCH_PROJECTS_FULFILLED = 'FETCH_PROJECTS_FULFILLED';
export const FETCH_PROJECTS_REJECTED = 'FETCH_PROJECTS_REJECTED';

export const FETCH_PROJECT_BY_ID = 'FETCH_PROJECT_BY_ID';
export const FETCH_PROJECT_BY_ID_PENDING = 'FETCH_PROJECT_BY_ID_PENDING';
export const FETCH_PROJECT_BY_ID_FULFILLED = 'FETCH_PROJECT_BY_ID_FULFILLED';
export const FETCH_PROJECT_BY_ID_REJECTED = 'FETCH_PROJECT_BY_ID_REJECTED';