export const FETCH_PROJECT = 'FETCH_PROJECT';
export const FETCH_PROJECT_PENDING = 'FETCH_PROJECT_PENDING';
export const FETCH_PROJECT_FULFILLED = 'FETCH_PROJECT_FULFILLED';
export const FETCH_PROJECT_REJECTED = 'FETCH_PROJECT_REJECTED';